# Generated by Django 4.1.1 on 2022-10-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodscategory',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
