# Generated by Django 4.1.1 on 2022-10-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_goodscategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, related_name='images', to='goods.goodsimages', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='size',
            field=models.ManyToManyField(blank=True, null=True, to='goods.goodssize', verbose_name='Размеры'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='goodsimages',
            order_with_respect_to=None,
        ),
        migrations.RemoveField(
            model_name='goodsimages',
            name='goods',
        ),
    ]
