# Generated by Django 4.1.1 on 2022-10-04 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_alter_goods_category_alter_goods_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='goods.goodscategory', verbose_name='Категория товара'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='size',
            field=models.ManyToManyField(blank=True, null=True, related_name='size', to='goods.goodssize', verbose_name='Размеры'),
        ),
    ]
