# Generated by Django 4.1.1 on 2022-10-04 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_alter_goods_category_alter_goods_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='images',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='size',
        ),
        migrations.RemoveField(
            model_name='goodscategory',
            name='slug',
        ),
        migrations.AddField(
            model_name='goodsimages',
            name='goods',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='goods.goods', verbose_name='Товары'),
        ),
        migrations.AddField(
            model_name='goodssize',
            name='goods',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='goods.goods', verbose_name='Товары'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='name',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Название товара'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='goodsimages',
            order_with_respect_to='goods',
        ),
    ]
