# Generated by Django 4.1.1 on 2022-10-04 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_remove_goods_images_remove_goods_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodssize',
            name='goods',
        ),
        migrations.AddField(
            model_name='goods',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='size', to='goods.goodssize', verbose_name='Размер'),
        ),
    ]
