# Generated by Django 4.1.1 on 2022-10-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_remove_goodssize_goods_goods_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='size',
        ),
        migrations.AddField(
            model_name='goods',
            name='size',
            field=models.ManyToManyField(blank=True, null=True, related_name='size', to='goods.goodssize', verbose_name='Размер'),
        ),
    ]
