# Generated by Django 4.1.1 on 2022-10-05 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_remove_goods_size_goods_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='category',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='goods.goodscategory', verbose_name='Категория товара'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goods',
            name='size',
            field=models.ManyToManyField(blank=True, related_name='size', to='goods.goodssize', verbose_name='Размер'),
        ),
    ]
