# Generated by Django 4.1.1 on 2022-10-13 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0010_alter_goodscategory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='size',
        ),
        migrations.AddField(
            model_name='goodssize',
            name='goods_size',
            field=models.ManyToManyField(blank=True, null=True, related_name='sizes', to='goods.goods', verbose_name='Размеры'),
        ),
    ]
