# Generated by Django 4.1.1 on 2022-10-13 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0011_alter_goodsimages_goods'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodscategory',
            options={'ordering': ['-id'], 'verbose_name': 'Категория товара', 'verbose_name_plural': 'Категории товаров'},
        ),
        migrations.AlterModelOptions(
            name='goodsimages',
            options={'ordering': ['-id'], 'verbose_name': 'Фото товара', 'verbose_name_plural': 'Фото товаров'},
        ),
        migrations.RenameField(
            model_name='goodssize',
            old_name='goods_size',
            new_name='size',
        ),
        migrations.AddField(
            model_name='goodsimages',
            name='image_goods',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_gallery', to='goods.goods', verbose_name='Товары'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='size',
            field=models.ManyToManyField(blank=True, null=True, related_name='goods_sizes', to='goods.goodssize', verbose_name='Размеры'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='goodsimages',
            order_with_respect_to=None,
        ),
        migrations.RemoveField(
            model_name='goodsimages',
            name='goods',
        ),
    ]
