# Generated by Django 4.1.1 on 2022-10-13 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0011_remove_goods_size_goodssize_goods_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodssize',
            name='goods_size',
        ),
        migrations.AddField(
            model_name='goods',
            name='size',
            field=models.ManyToManyField(blank=True, null=True, related_name='goods_sizes', to='goods.goodssize', verbose_name='Размеры'),
        ),
    ]
