# Generated by Django 4.1.1 on 2022-11-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0012_remove_goodssize_goods_size_goods_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodscategory',
            options={'ordering': ['id'], 'verbose_name': 'Категория товара', 'verbose_name_plural': 'Категории товаров'},
        ),
        migrations.AlterModelOptions(
            name='goodsimages',
            options={'ordering': ['id'], 'verbose_name': 'Фото товара', 'verbose_name_plural': 'Фото товаров'},
        ),
        migrations.AlterField(
            model_name='goods',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена'),
        ),
    ]
