# Generated by Django 4.1.1 on 2022-10-13 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0012_alter_goodscategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodscategory',
            options={'ordering': ['id'], 'verbose_name': 'Категория товара', 'verbose_name_plural': 'Категории товаров'},
        ),
        migrations.AlterField(
            model_name='goods',
            name='size',
            field=models.ManyToManyField(blank=True, null=True, related_name='sizes', to='goods.goodssize', verbose_name='Размеры'),
        ),
    ]
