# Generated by Django 4.1.1 on 2022-10-17 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0013_alter_goodscategory_options_alter_goods_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='size',
            field=models.ManyToManyField(blank=True, null=True, related_name='goods_sizes', to='goods.goodssize', verbose_name='Размеры'),
        ),
    ]
