# Generated by Django 4.1.1 on 2022-11-16 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0015_alter_goodsimages_options_alter_goods_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='discount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Размер скидки'),
        ),
        migrations.AddField(
            model_name='goods',
            name='new_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Новая цена'),
        ),
    ]
