# Generated by Django 4.1.1 on 2022-11-16 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0016_goods_discount_goods_new_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='new',
            field=models.BooleanField(default=1, verbose_name='Новинка'),
            preserve_default=False,
        ),
    ]
