# Generated by Django 4.1.1 on 2022-12-11 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    def reorder(apps, schema_editor):
        Goods = apps.get_model("goods", "Goods")
        for order, item in enumerate(Goods.objects.all(), 1):
            item.my_order = order
            item.save(update_fields=['my_order'])

    dependencies = [
        ('goods', '0017_goods_new'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'ordering': ['my_order'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AddField(
            model_name='goods',
            name='my_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Сорт.'),
        ),
        migrations.RunPython(reorder, reverse_code=migrations.RunPython.noop),
    ]
