# Generated by Django 4.1.1 on 2022-11-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='counter',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Писем отправлено'),
        ),
        migrations.AddField(
            model_name='mail',
            name='heading',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='mail',
            name='image',
            field=models.ImageField(default=0, max_length=255, upload_to='images/', verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mail',
            name='sub_heading',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='mail',
            name='test_mailing',
            field=models.BooleanField(default=False, verbose_name='Тестовая рассылка'),
        ),
        migrations.AddField(
            model_name='userlist',
            name='test_user',
            field=models.BooleanField(default=False, verbose_name='Тестовый поьзователь'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата отправки'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='subject',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Тема письма'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст письма'),
        ),
    ]
