# Generated by Django 4.1.1 on 2022-11-14 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='counter',
            field=models.IntegerField(blank=True, null=True, verbose_name='Писем отправлено'),
        ),
    ]
