# Generated by Django 4.1.1 on 2022-11-14 18:24

from django.db import migrations, models
import mail.models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_mail_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='heading',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='mail',
            name='image',
            field=models.ImageField(default=1, max_length=255, upload_to=mail.models.image_directory_path, verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mail',
            name='sub_heading',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата отправки'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='subject',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Тема письма'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст письма'),
        ),
    ]
