# Generated by Django 4.1.1 on 2022-11-16 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_mail_heading_mail_image_mail_sub_heading_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='image',
            field=models.ImageField(max_length=255, upload_to='images/', verbose_name='Изображение'),
        ),
    ]
