# Generated by Django 4.1.1 on 2022-11-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0004_alter_mail_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='counter',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Писем отправлено'),
        ),
    ]
