# Generated by Django 4.1.1 on 2022-11-17 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0005_alter_mail_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlist',
            name='test_user',
            field=models.BooleanField(default=False, verbose_name='Тестовый поьзователь'),
        ),
    ]
