# Generated by Django 4.1.1 on 2022-11-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0006_userlist_test_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='test_mailing',
            field=models.BooleanField(default=False, verbose_name='Тестовая рассылка'),
        ),
    ]
