# Generated by Django 4.1.1 on 2022-11-29 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0008_rename_e_mail_userlist_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlist',
            name='email',
        ),
        migrations.AddField(
            model_name='userlist',
            name='e_mail',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
    ]
