# Generated by Django 4.1.1 on 2022-11-29 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0009_remove_userlist_email_userlist_e_mail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlist',
            old_name='e_mail',
            new_name='email',
        ),
    ]
