# Generated by Django 4.1.1 on 2022-10-17 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя клиента')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='Город')),
                ('address1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('address2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес дополнительно')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('extra', models.TextField(blank=True, null=True, verbose_name='Дополнительная информация')),
                ('orders', models.TextField(blank=True, null=True, verbose_name='Заказы')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
