# Generated by Django 4.1.1 on 2022-10-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Завершен'),
        ),
    ]
