# Generated by Django 4.1.1 on 2022-10-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orders_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='shipping',
            field=models.TextField(blank=True, null=True, verbose_name='Доставка'),
        ),
    ]
