# Generated by Django 4.1.1 on 2022-10-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orders_shipping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='shipping',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Доставка'),
        ),
    ]
