# Generated by Django 4.1.1 on 2023-01-31 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_promo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='discount',
            field=models.PositiveIntegerField(blank=True, default=10, null=True, verbose_name='Размер скидки %'),
        ),
    ]
