# Generated by Django 4.1.1 on 2023-02-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_promo_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='messages_sent',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Писем отправлено'),
        ),
    ]
