# Generated by Django 4.1.1 on 2023-02-03 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_orders_messages_sent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Promo',
        ),
    ]
