# Generated by Django 4.1.1 on 2022-11-28 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Текст 1')),
                ('text_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Текст 2')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
            },
        ),
    ]
