# Generated by Django 4.1.1 on 2023-01-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0002_commercial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_title', models.CharField(blank=True, max_length=20, null=True, verbose_name='Предзаголовок')),
                ('title', models.CharField(blank=True, max_length=20, null=True, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=20, null=True, verbose_name='Подзаголовок')),
                ('url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Изображение')),
                ('button_text', models.TextField(blank=True, null=True, verbose_name='Текст кнопки')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активный')),
                ('my_order', models.PositiveIntegerField(default=0, verbose_name='Сорт.')),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Слайды',
                'ordering': ['my_order'],
            },
        ),
    ]
