# Generated by Django 4.1.1 on 2023-01-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0003_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='button_text',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Текст кнопки'),
        ),
    ]
