# Generated by Django 4.1.1 on 2023-02-27 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0004_alter_slider_button_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='subtitle',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Подзаголовок'),
        ),
    ]
